window.env = {
    REACT_APP_ENV: "$ENV",
    REACT_APP_TITLE: "$APP_TITLE",
    REACT_APP_DESCRIPTION_CONTENT: "$DESCRIPTION",
    REACT_APP_API_BASE_URL: "$API_BASE_URL",
    REACT_APP_LOGIN_CLIENT_ID: "$CLIENT_ID",
    REACT_APP_CLIENT_ID: "$CLIENT_ID",
    REACT_APP_CLIENT_SECRET: "$CLIENT_SECRET",
    REACT_APP_MULTI_LANGS_SUPPORT : "$MULTI_LANGS_SUPPORT",
    REACT_APP_PRELOAD_LANG : "$PRELOAD_LANG",
    REACT_APP_LANGS_SUPPORT : "$LANGS_SUPPORT",
    REACT_APP_DEFAULT_THEME : "$DEFAULT_THEME",
    REACT_APP_SYSTEM_EMAIL_ADDRESS : "$REGISTER_EMAIL_ADDRESS",
    REACT_APP_REFERENCE_FIAT_CURRENCY : "$REFERENCE_FIAT_CURRENCY",
    REACT_APP_CALENDAR_TYPE : "$CALENDAR_TYPE",

}