//main reducer actions
export const SET_THEME = "SET_THEME";
export const SET_LOADING = "SET_LOADING";
export const SET_THEME_INITIATE = "SET_THEME_INITIATE";

export const SET_ACTIVE_PAIR = "SET_ACTIVE_PAIR";
export const SET_ACTIVE_PAIR_INITIATE = "SET_ACTIVE_PAIR_INITIATE";
export const LOAD_CONFIG = "LOAD_CONFIG";

export const SET_BUY_ORDERS = "SET_BUY_ORDERS";
export const SET_SELL_ORDERS = "SET_SELL_ORDERS";

export const SET_BEST_BUY_PRICE = "SET_BEST_BUY_PRICE";
export const SET_BEST_SELL_PRICE = "SET_BEST_SELL_PRICE";
export const SET_LAST_TRADE_PRICE = "SET_LAST_TRADE_PRICE";

export const SET_PANEL_TOKENS = "SET_PANEL_TOKENS";
export const SET_PANEL_TOKENS_INITIATE = "SET_PANEL_TOKENS_INITIATE";

//auth reducer actions
export const SET_USER_ACCOUNT_INFO = "SET_USER_ACCOUNT_INFO";

export const SET_USER_TOKENS = "SET_USER_TOKENS";
export const SET_USER_TOKENS_INITIATE = "SET_USER_TOKENS_INITIATE";
export const SET_USER_INFO = "SET_USER_INFO";
export const SET_USER_INFO_INITIATE = "SET_USER_INFO_INITIATE";

export const SET_LAST_TRANSACTION = "SET_LAST_TRANSACTION";

export const LOGIN_INITIATE = "LOGIN_INITIATE";
export const LOGOUT = "LOGOUT";
export const LOGOUT_INITIATE = "LOGOUT_INITIATE";
